"""Write logic in task.py and fixed user.py

Revision ID: bd78f00e4707
Revises: 75d993b547bd
Create Date: 2024-09-27 02:16:36.510340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd78f00e4707'
down_revision: Union[str, None] = '75d993b547bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
